### ISSUE TITLE
Safari: SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by kontrollanten** [hitta-skyddsrum/webclient-preact#137]
https://sentry.io/hitta-skyddsrum/webclient/issues/588557926/?referrer=github_plugin

```
SecurityError: The operation is insecure.
  at dispatch (./middlewares/state-persist/index.js:20:8)
  at call (./containers/app.js:15:17)
  at init (./index.js:7:13)
  at afterFill (./index.js:31:5)
  at call (./index.js:18:1)
...
(9 additional frame(s) were not displayed)
```

https://github.com/angular-translate/angular-translate/commit/75504cbe2ddc0d18e08288b0fa4453356aaafe73

**Comment by kontrollanten** [comment]
Sentry issue: [WEBCLIENT-6Z](https://sentry.io/hitta-skyddsrum/webclient/issues/659230039/?referrer=github_plugin)
