### ISSUE TITLE
TypeError: Cannot read property 'firstChild' of null

### ISSUE THREAD

**Issue by kontrollanten** [hitta-skyddsrum/webclient-preact#40]
https://sentry.io/hitta-skyddsrum/preact/issues/482469590/

```
TypeError: Cannot read property 'firstChild' of null
  at e.t (/main.js:1:483068)
  at HTMLDivElement.r (/main.js:1:382262)
```

**Comment by kontrollanten** [comment]
https://sentry.io/hitta-skyddsrum/preact/issues/480752516/
