### ISSUE TITLE
TypeError: Cannot read property 'lat' of undefined

### ISSUE THREAD

**Issue by kontrollanten** [hitta-skyddsrum/webclient-preact#41]
https://sentry.io/hitta-skyddsrum/preact/issues/482286839/

```
TypeError: Cannot read property 'lat' of undefined
  at None (/main.js:1:480024)
  at Array.map (<anonymous>)
  at M.e.default [as constructor] (/main.js:1:479945)
  at M.S [as render] (/main.js:1:155113)
  at k (/main.js:1:156027)
...
(11 additional frame(s) were not displayed)
```

**Comment by kontrollanten** [comment]
Solved by #39
